import Array from './Array';
import Function from './Function';
import HTMLElement from './HTMLElement';
import JSON from './JSON';
import Number from './Number';
import Object from './Object';
import Promise from './Promise';
import String from './String';
import URL from './URL';
export { Array, Function, HTMLElement, JSON, Number, Object, Promise, String, URL };